title = 'DeNS'
languageCode = 'en-us'
baseURL = 'https://mlabs-haskell.github.io/DeNS/'

[module]
proxy = "direct"

[[module.imports]]
path = "github.com/google/docsy"

[[module.mounts]]
source = 'content'
target = 'content'

[[module.mounts]]
source = '../doc'
target = 'content/docs/architecture'

[[module.mounts]]
source = '../dens-query/doc'
target = 'content/docs/dens-query'

[[module.mounts]]
source = '../dens-transactions/doc'
target = 'content/docs/dens-transactions'

[[module.mounts]]
source = '../dens-apps/pdns/dens-pdns-backend/doc'
target = 'content/docs/dens-pdns-backend'

[markup.asciidocExt]
backend = 'html5'
extensions = []
failureLevel = 'warn'
noHeaderOrFooter = true
preserveTOC = false
safeMode = 'unsafe'
sectionNumbers = false
trace = false
verbose = false
workingFolderCurrent = true

[markup.asciidocExt.attributes]

[security.exec]
allow = ['^go$', '^asciidoctor$', '^npx$']

[params]
offlineSearch = true

[params.ui]
navbar_logo = false
