+++
title = "Milestone 5"
weight = 5
+++

:toc:
:relfilesuffix: /

== Deployment, Documentation, Productionizing
[cols="1,3a"]
|===

// Milestone outputs
^|Milestone Outputs
|

1. A deployment-ready package or container (Nix/Docker) is made available for users 

** Such packages are all available with Nix as a flake output:

*** https://github.com/mlabs-haskell/DeNS/blob/f5a8c6f419dffdd77b052f74d80e9824842e1bca/dens-query/build.nix#L45[dens-query-cli]

*** https://github.com/mlabs-haskell/DeNS/blob/f5a8c6f419dffdd77b052f74d80e9824842e1bca/dens-transactions/build.nix#L26[dens-transactions-cli]

*** https://github.com/mlabs-haskell/DeNS/blob/main/dens-apps/pdns/dens-pdns-backend/build.nix#L38[dens-pdns-backend]

** Docker images and a Compose file to run the system on the Preview testnet are available https://github.com/mlabs-haskell/DeNS/blob/b4fbf713e6289ca57786140fe4201819e8ae2266/dens-apps/preview-testnet/build.nix[here]

2. Extensive tests, including golden tests where applicable/useful, are implemented for each of the DeNS components

** An integration test suite which verifies data is piped between each component correctly can be found https://github.com/mlabs-haskell/DeNS/tree/656a29b39581e97dc9403d3ddfbf882a79c62a56/dens-testsuites/integration[here]

** A test suite for DeNS Query's to verify the SQL queries function as expected can be found https://github.com/mlabs-haskell/DeNS/tree/f12e3f85e3ed666bd3d8a7b06966babe7071d640/dens-query/src/Tests[here]

** A PowerDNS backend test suite to verify that DeNS Query's SQL schema integrates with PowerDNS can be found https://github.com/mlabs-haskell/DeNS/tree/76cc117681bde6c23c76a360ee997c1124db92b3/dens-apps/pdns/dens-pdns-backend/src/tests[here]

3. User-facing documentation & examples are provided 

** A website with user-facing documentation and examples can be found xref:../../../../DeNS.adoc[here]

4. A running service (the exact nature depends on design decisions, provisionally: a DeNS "local resolver") that users can integrate with to perform name-resolution queries using our system. 

** A running service is demonstrated on the Preview testnet with the Docker images and Compose file mentioned above.

// Acceptance criteria

^|Acceptance criteria
|

* The package / container is properly configured and can be deployed by users to interact with the DeNS protocol. 

** The demo video <<_preview_testnet_demo_video>> demonstrates this.

* The test suites are extensive and all tests pass. 

** CI on the most recent https://hercules-ci.com/github/mlabs-haskell/DeNS/jobs/575[commit] (at the time of writing this) passes and hence demonstrates that all tests pass.

* Documentation is clear, thorough, and sufficient for users to interact with the protocol.

** The project website provided found xref:../../../../DeNS.adoc[here] has such documentation.

* The running service actually works. 

** The demo video <<_preview_testnet_demo_video>> demonstrates this.


// Evidence of milestone completion
^|Evidence of milestone completion
|

* 1-2: A link to a commit where the objectives of the milestone are achieved. 

** Commits which demonstrate completion of 1-2 are as follows.

*** https://github.com/mlabs-haskell/DeNS/blob/f5a8c6f419dffdd77b052f74d80e9824842e1bca/dens-query/build.nix#L45[Implementation of `dens-query-cli`]

*** https://github.com/mlabs-haskell/DeNS/blob/f5a8c6f419dffdd77b052f74d80e9824842e1bca/dens-transactions/build.nix#L26[Implementation of `dens-transactions-cli`]

*** https://github.com/mlabs-haskell/DeNS/blob/main/dens-apps/pdns/dens-pdns-backend/build.nix#L38[Implementation of `dens-pdns-backend`]

*** https://github.com/mlabs-haskell/DeNS/blob/b4fbf713e6289ca57786140fe4201819e8ae2266/dens-apps/preview-testnet/build.nix[Docker images to orchestrate the services]

*** https://github.com/mlabs-haskell/DeNS/tree/656a29b39581e97dc9403d3ddfbf882a79c62a56/dens-testsuites/integration[Integration test suite]

*** https://github.com/mlabs-haskell/DeNS/tree/f12e3f85e3ed666bd3d8a7b06966babe7071d640/dens-query/src/Tests[DeNS Query test suite]

*** https://github.com/mlabs-haskell/DeNS/tree/76cc117681bde6c23c76a360ee997c1124db92b3/dens-apps/pdns/dens-pdns-backend/src/tests[PowerDNS backend test suite]

* 3: A link to the documentation website. 

** The documentation website can be found https://mlabs-haskell.github.io/DeNS/[here]

* 4: A demonstration video or set of network logs that clearly show the service in operation. 

** The demo video <<_preview_testnet_demo_video>> demonstrates this.

* 5: We will show the Cardano community an open-source, well-documented, blockchain-based name resolution service that improves on the privacy and security of DNS. 

** Evidence is presented above.

|===

=== Preview Testnet Demo Video

video::eTrLvzYJs3I[youtube]

The video can be found https://youtu.be/eTrLvzYJs3I[here]


==== Commands Used

The following commands were executed in the demo video.

NOTE: It is assumed that we start in the root of the project directory.

. Load all the docker images.
+
[source,shell]
```
cd dens-apps/preview-testnet
nix build .#cardano-node-preview-testnet-image && docker load < ./result
nix build .#ogmios-preview-testnet-image && docker load < ./result
nix build .#dens-query-preview-testnet-image && docker load < ./result
nix build .#dens-pdns-preview-testnet-image && docker load < ./result
nix build .#dens-pdns-backend-preview-testnet-image && docker load  < ./result
nix build .#dens-query-postgres-preview-testnet-image && docker load < ./result
```
+
NOTE: These commands were done prior to filming the demo video

. Run all services using the https://docs.docker.com/compose/compose-file[Compose file].
+
[source,shell]
```
docker compose up
```

. Wait several hours for the services to sync with the preview testnet.

. Check that `+testdomainname.com+` has no RRs associated with it using the well known DNS lookup utility `+dig+`.
+
[source,shell]
```
dig @127.0.0.1 -p 6653 testdomainname.com
```
+
IMPORTANT: The Compose file maps the port 6653 on the host machine to the PowerDNS server running in the docker image.

. Purchase the domain name `+testdomainname.com+`
+
[source,shell]
```
docker exec -it preview-testnet-dens-query-1 \
    dens-transactions-cli \
        register-domain \
        --ogmios-host ogmios \
        --ogmios-port 1337 \
        --network Preview \
        --protocol-nft-tx-out-ref "5969b450ec00019044fbcb1cd5973cc80a47b1507e2e0e14f3e6e4a2f23cdabd#0" \
        --dens-query-socket-path /ipc/dens-query/dens-query.sock \
        --private-key-bech32 ed25519_sk1p8874wgza2c5yxytucugt2k2mrw3l3gkpg6ezxn498smerqh8j0qe078pu \
        --domain-name testdomainname.com
```

. Associate `+testdomainname.com+` with some RRs
+
[source,shell]
```
docker exec -it preview-testnet-dens-query-1 \
    dens-transactions-cli \
        update-record \
        --ogmios-host ogmios \
        --ogmios-port 1337 \
        --network Preview \
        --protocol-nft-tx-out-ref "5969b450ec00019044fbcb1cd5973cc80a47b1507e2e0e14f3e6e4a2f23cdabd#0" \
        --dens-query-socket-path /ipc/dens-query/dens-query.sock \
        --private-key-bech32 ed25519_sk1p8874wgza2c5yxytucugt2k2mrw3l3gkpg6ezxn498smerqh8j0qe078pu \
        --domain-name testdomainname.com \
        --a-record "270,69.69.69.69" \
        --soa-record "30,ns1.testdomainname.com dns-admin.testdomainname.com 639491960 900 900 1800 60"
```
. Verify that `+testdomainname.com+` has the RRs we just associated it with.
+
[source,shell]
```
dig @127.0.0.1 -p 6653 testdomainname.com
```

===== Logs
The terminal output of the demo is as follows.

[source,shell]
```
$ dig @127.0.0.1 -p 6653 testdomainname.com

; <<>> DiG 9.18.19 <<>> @127.0.0.1 -p 6653 testdomainname.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 11316
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;testdomainname.com.		IN	A

;; Query time: 2 msec
;; SERVER: 127.0.0.1#6653(127.0.0.1) (UDP)
;; WHEN: Wed Jun 05 02:40:22 MDT 2024
;; MSG SIZE  rcvd: 47

$ docker exec -it preview-testnet-dens-query-1 \
    dens-transactions-cli \
        register-domain \
        --ogmios-host ogmios \
        --ogmios-port 1337 \
        --network Preview \
        --protocol-nft-tx-out-ref "5969b450ec00019044fbcb1cd5973cc80a47b1507e2e0e14f3e6e4a2f23cdabd#0" \
        --dens-query-socket-path /ipc/dens-query/dens-query.sock \
        --private-key-bech32 ed25519_sk1p8874wgza2c5yxytucugt2k2mrw3l3gkpg6ezxn498smerqh8j0qe078pu \
        --domain-name testdomainname.com
(node:136) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
info: Tx hash: 9bda385ff825254f416b7c2275e0c4277c6493224ea83163ab724f21a4b6a4da
[02:40 AM] [jared@pletbjerg ~/Documents/Work/DeNS/dens-apps/preview-testnet]$ docker exec -it preview-testnet-dens-query-1 \
    dens-transactions-cli \
        update-record \
        --ogmios-host ogmios \
        --ogmios-port 1337 \
        --network Preview \
        --protocol-nft-tx-out-ref "5969b450ec00019044fbcb1cd5973cc80a47b1507e2e0e14f3e6e4a2f23cdabd#0" \
        --dens-query-socket-path /ipc/dens-query/dens-query.sock \
        --private-key-bech32 ed25519_sk1p8874wgza2c5yxytucugt2k2mrw3l3gkpg6ezxn498smerqh8j0qe078pu \
        --domain-name testdomainname.com \
        --a-record "270,69.69.69.69" \
        --soa-record "30,ns1.testdomainname.com dns-admin.testdomainname.com 639491960 900 900 1800 60"
(node:158) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
info: Tx hash: 6414ea74af6ecc214fdac327b5abca8be80f6b9f9dbdb5ec920cedded343a349
$ dig @127.0.0.1 -p 6653 testdomainname.com

; <<>> DiG 9.18.19 <<>> @127.0.0.1 -p 6653 testdomainname.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 14626
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;testdomainname.com.		IN	A

;; Query time: 1 msec
;; SERVER: 127.0.0.1#6653(127.0.0.1) (UDP)
;; WHEN: Wed Jun 05 02:42:02 MDT 2024
;; MSG SIZE  rcvd: 47

$ dig @127.0.0.1 -p 6653 testdomainname.com

; <<>> DiG 9.18.19 <<>> @127.0.0.1 -p 6653 testdomainname.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 5485
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;testdomainname.com.		IN	A

;; Query time: 1 msec
;; SERVER: 127.0.0.1#6653(127.0.0.1) (UDP)
;; WHEN: Wed Jun 05 02:42:25 MDT 2024
;; MSG SIZE  rcvd: 47

$ dig @127.0.0.1 -p 6653 testdomainname.com

; <<>> DiG 9.18.19 <<>> @127.0.0.1 -p 6653 testdomainname.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13253
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;testdomainname.com.		IN	A

;; ANSWER SECTION:
testdomainname.com.	270	IN	A	69.69.69.69

;; Query time: 20 msec
;; SERVER: 127.0.0.1#6653(127.0.0.1) (UDP)
;; WHEN: Wed Jun 05 02:42:33 MDT 2024
;; MSG SIZE  rcvd: 63
```
